spring.application.name=electrocyb_backend
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?user=postgres.lwodpsjxfpjicjelyygi&password=e4jwuay3d7cx
spring.datasource.username=postgres
spring.datasource.password=e4jwuay3d7cx
spring.datasource.driver-class-name=org.postgresql.Driver
# Esto le dice a Java que prefiera IPv4
#java.net.preferIPv4Stack=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.properties.hibernate.format_sql=true

spring.web.locale=es_PE
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=electrocyb@gmail.com
spring.mail.password=rouy fzrx hzfr bxwh     
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

# Opcional pero útil:
spring.mail.default-encoding=UTF-8
