spring.application.name=electrocyb_backend
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?user=postgres.lwodpsjxfpjicjelyygi&password=e4jwuay3d7cx&sslmode=require&prepareThreshold=0&preparedStatementCacheQueries=0
spring.datasource.username=postgres
spring.datasource.password=e4jwuay3d7cx
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=20000

# Esto le dice a Java que prefiera IPv4
#java.net.preferIPv4Stack=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.properties.hibernate.format_sql=true

spring.web.locale=es_PE
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=electrocyb@gmail.com
spring.mail.password=lnam aanv vicv djgh   
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

openai.api.key=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
openai.base.url=https://api.openai.com/v1
openai.model=gpt-4o-mini

#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

# Opcional pero útil:
spring.mail.default-encoding=UTF-8
